// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkSEN64ejHkmNj7dajEjRWWlUvK0i0gY8',
    appId: '1:426679750742:web:2eb133bd85685b7b83ebf7',
    messagingSenderId: '426679750742',
    projectId: 'flutter-test-f3055',
    authDomain: 'flutter-test-f3055.firebaseapp.com',
    databaseURL: 'https://flutter-test-f3055-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-f3055.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU2veJR7t8shXkiGKZr1ntYiGhVN6Jg5w',
    appId: '1:426679750742:android:34c875595089a03683ebf7',
    messagingSenderId: '426679750742',
    projectId: 'flutter-test-f3055',
    databaseURL: 'https://flutter-test-f3055-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-f3055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKeOzQua4cVWRoSsddcmI7NyQEzZBsMn8',
    appId: '1:426679750742:ios:2fe0e6da90d7fecd83ebf7',
    messagingSenderId: '426679750742',
    projectId: 'flutter-test-f3055',
    databaseURL: 'https://flutter-test-f3055-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-f3055.appspot.com',
    iosBundleId: 'com.luchks.yapecausa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKeOzQua4cVWRoSsddcmI7NyQEzZBsMn8',
    appId: '1:426679750742:ios:2fe0e6da90d7fecd83ebf7',
    messagingSenderId: '426679750742',
    projectId: 'flutter-test-f3055',
    databaseURL: 'https://flutter-test-f3055-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-f3055.appspot.com',
    iosBundleId: 'com.luchks.yapecausa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkSEN64ejHkmNj7dajEjRWWlUvK0i0gY8',
    appId: '1:426679750742:web:7e3f2288da8dc53283ebf7',
    messagingSenderId: '426679750742',
    projectId: 'flutter-test-f3055',
    authDomain: 'flutter-test-f3055.firebaseapp.com',
    databaseURL: 'https://flutter-test-f3055-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-f3055.appspot.com',
  );
}
